### ISSUE TITLE
I can install it with 'Vundle'?

### ISSUE THREAD

**Issue by brujo696** [matthewsimo/angular-vim-snippets#16]

**Comment by matthewsimo** [comment]
No idea - I don't use Vundle so I have no idea about the implementation details there. Give it a shot and let me know. If not, feel free to fork and submit a branch with potential changes, I can review things and we can continue to talk about adding support. Please update this issue after you've explored.

**Comment by Delapouite** [comment]
@brujo696 Just use 

Bundle 'matthewsimo/angular-vim-snippets'

and it should work.

**Comment by brujo696** [comment]
thanks
